Feature/order view - Order 주문내역 상세 조회(주문 식재료)
phdljr/one-click-recipe pull request #51
Opened 2024-01-11 12:47 UTC by baegyutae

## #️⃣연관된 이슈
> ex) `#이슈번호, #이슈번호`</br>
> 해당 PR이 닫힐 때, 이슈도 닫히게 하고싶다면? ex) `close #이슈번호, #이슈번호`

- 주문내역 상세 조회(주문 식재료) 

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- OrderDetails 연결

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

-

2024-01-11 16:17 UTC, phdljr requested changes
고생하셨습니다!
리뷰확인 부탁드립니다~

2024-01-11 16:17 UTC, phdljr commented on src/main/java/org/springeel/oneclickrecipe/domain/order/dto/service/OrderReadResponseDto.java
> +    List<OrderDetailDto> orderDetails // 주문 상세 정보를 담을 리스트
목록 조회에서는 OrderDetailDto를 조회할 필요가 없을 것 같습니다.
단일 조회에 추가해보시는게 어떨까요?

2024-01-11 17:42 UTC, pangseon reviewed
수고하셨습니다 리뷰 확인 부탁드릴게요~

2024-01-11 17:42 UTC, pangseon commented on src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
> +    @PostMapping("")
URL 사용안하시면 ()지워주셔도 될 것 같습니다!

2024-01-11 17:42 UTC, pangseon commented on src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
> +    @GetMapping("")
URL을 orderslist로 변경하면 어떨까요?

2024-01-11 17:42 UTC, pangseon commented on src/main/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImpl.java
> +            .orElseThrow(() -> new EntityNotFoundException("Order not found for id: " + orderId));
EntityNotFoundException 대신 커스텀Exception을 사용하는건 어떨까요?

2024-01-11 17:42 UTC, pangseon commented on src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
> +    @GetMapping("")
주문 내역 목록 조회를 한다면 유저가 주문한 내역에 대한 조회를 하는건가요?
유저가 주문한 주문 내역 전체를 조회할때는 {userId}를 쓰는건 어떨까요?

2024-01-12 01:43 UTC, baegyutae commented on src/main/java/org/springeel/oneclickrecipe/domain/order/dto/service/OrderReadResponseDto.java
> +    List<OrderDetailDto> orderDetails // 주문 상세 정보를 담을 리스트
넵! 수정했습니당

2024-01-12 01:43 UTC, baegyutae commented on src/main/java/org/springeel/oneclickrecipe/domain/order/service/impl/OrderServiceImpl.java
> +            .orElseThrow(() -> new EntityNotFoundException("Order not found for id: " + orderId));
앗 그럼 예외처리 이슈카드를 따로 만들어서  주문 파트 전역에 코드 추가 후 PR 다시 하겠습니다!

2024-01-12 01:45 UTC, phdljr approved these changes

2024-01-12 02:26 UTC, baegyutae commented on src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
> +    @PostMapping("")
네 알겠습니당! 시정하겠습니다!

2024-01-12 03:01 UTC, baegyutae commented on src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
> +    @GetMapping("")
네 시정했습니다!

2024-01-12 03:49 UTC, pangseon approved these changes
수고하셨습니다~

2024-01-12 03:49 UTC, pangseon commented on src/main/java/org/springeel/oneclickrecipe/domain/order/controller/OrderController.java
> +            userDetailsImpl.user()
49,50 번째 줄 같이 합쳐 주시면 좋을것같습니다.
userDeatilsImpl.user().getId()

2024-01-12 03:51 UTC, merged